#pragma GCC poison CONFIG_AC97
#pragma GCC poison CONFIG_AHCI
#pragma GCC poison CONFIG_AHCI_ICH9
#pragma GCC poison CONFIG_ATI_VGA
#pragma GCC poison CONFIG_BITBANG_I2C
#pragma GCC poison CONFIG_BOCHS_DISPLAY
#pragma GCC poison CONFIG_CAN_BUS
#pragma GCC poison CONFIG_CAN_CTUCANFD
#pragma GCC poison CONFIG_CAN_CTUCANFD_PCI
#pragma GCC poison CONFIG_CAN_PCI
#pragma GCC poison CONFIG_CAN_SJA1000
#pragma GCC poison CONFIG_DDC
#pragma GCC poison CONFIG_DWC_SDMMC
#pragma GCC poison CONFIG_E1000_PCI
#pragma GCC poison CONFIG_EDID
#pragma GCC poison CONFIG_EEPRO100_PCI
#pragma GCC poison CONFIG_ES1370
#pragma GCC poison CONFIG_ESP
#pragma GCC poison CONFIG_ESP_PCI
#pragma GCC poison CONFIG_GENERIC_LOADER
#pragma GCC poison CONFIG_GUEST_LOADER
#pragma GCC poison CONFIG_HDA
#pragma GCC poison CONFIG_I2C
#pragma GCC poison CONFIG_I386_DIS
#pragma GCC poison CONFIG_I82801B11
#pragma GCC poison CONFIG_IDE_CORE
#pragma GCC poison CONFIG_IDE_QDEV
#pragma GCC poison CONFIG_IMX_USBPHY
#pragma GCC poison CONFIG_IPACK
#pragma GCC poison CONFIG_LED
#pragma GCC poison CONFIG_LSI_SCSI_PCI
#pragma GCC poison CONFIG_MEGASAS_SCSI_PCI
#pragma GCC poison CONFIG_MPTSAS_SCSI_PCI
#pragma GCC poison CONFIG_NE2000_COMMON
#pragma GCC poison CONFIG_NE2000_PCI
#pragma GCC poison CONFIG_NMC93XX_EEPROM
#pragma GCC poison CONFIG_NVME_PCI
#pragma GCC poison CONFIG_OPENCORES_ETH
#pragma GCC poison CONFIG_PCI
#pragma GCC poison CONFIG_PCI_DEVICES
#pragma GCC poison CONFIG_PCI_EXPRESS
#pragma GCC poison CONFIG_PCI_EXPRESS_GENERIC_BRIDGE
#pragma GCC poison CONFIG_PCNET_COMMON
#pragma GCC poison CONFIG_PCNET_PCI
#pragma GCC poison CONFIG_PFLASH_CFI01
#pragma GCC poison CONFIG_PVPANIC_COMMON
#pragma GCC poison CONFIG_PVPANIC_PCI
#pragma GCC poison CONFIG_RTL8139_PCI
#pragma GCC poison CONFIG_SCSI
#pragma GCC poison CONFIG_SD
#pragma GCC poison CONFIG_SDHCI
#pragma GCC poison CONFIG_SDHCI_PCI
#pragma GCC poison CONFIG_SEMIHOSTING
#pragma GCC poison CONFIG_SERIAL
#pragma GCC poison CONFIG_SERIAL_PCI
#pragma GCC poison CONFIG_SERIAL_PCI_MULTI
#pragma GCC poison CONFIG_SSI
#pragma GCC poison CONFIG_SSI_M25P80
#pragma GCC poison CONFIG_SYSTEM_ONLY
#pragma GCC poison CONFIG_TMP105
#pragma GCC poison CONFIG_TULIP
#pragma GCC poison CONFIG_UNIMP
#pragma GCC poison CONFIG_USB
#pragma GCC poison CONFIG_USB_AUDIO
#pragma GCC poison CONFIG_USB_CANOKEY
#pragma GCC poison CONFIG_USB_EHCI
#pragma GCC poison CONFIG_USB_EHCI_PCI
#pragma GCC poison CONFIG_USB_NETWORK
#pragma GCC poison CONFIG_USB_OHCI
#pragma GCC poison CONFIG_USB_OHCI_PCI
#pragma GCC poison CONFIG_USB_SERIAL
#pragma GCC poison CONFIG_USB_SMARTCARD
#pragma GCC poison CONFIG_USB_STORAGE_BOT
#pragma GCC poison CONFIG_USB_STORAGE_CLASSIC
#pragma GCC poison CONFIG_USB_STORAGE_CORE
#pragma GCC poison CONFIG_USB_STORAGE_MTP
#pragma GCC poison CONFIG_USB_STORAGE_UAS
#pragma GCC poison CONFIG_USB_TABLET_WACOM
#pragma GCC poison CONFIG_USB_U2F
#pragma GCC poison CONFIG_USB_UHCI
#pragma GCC poison CONFIG_USB_XHCI
#pragma GCC poison CONFIG_USB_XHCI_NEC
#pragma GCC poison CONFIG_USB_XHCI_PCI
#pragma GCC poison CONFIG_VGA
#pragma GCC poison CONFIG_VGA_CIRRUS
#pragma GCC poison CONFIG_VGA_PCI
#pragma GCC poison CONFIG_VIRTIO
#pragma GCC poison CONFIG_VIRTIO_BALLOON
#pragma GCC poison CONFIG_VIRTIO_BLK
#pragma GCC poison CONFIG_VIRTIO_CRYPTO
#pragma GCC poison CONFIG_VIRTIO_GPU
#pragma GCC poison CONFIG_VIRTIO_INPUT
#pragma GCC poison CONFIG_VIRTIO_IOMMU
#pragma GCC poison CONFIG_VIRTIO_NET
#pragma GCC poison CONFIG_VIRTIO_PCI
#pragma GCC poison CONFIG_VIRTIO_RNG
#pragma GCC poison CONFIG_VIRTIO_SCSI
#pragma GCC poison CONFIG_VIRTIO_SERIAL
#pragma GCC poison CONFIG_VMW_PVSCSI_SCSI_PCI
#pragma GCC poison CONFIG_VMXNET3_PCI
#pragma GCC poison CONFIG_WDT_IB6300ESB
#pragma GCC poison CONFIG_XTENSA_DIS
#pragma GCC poison CONFIG_XTENSA_ESP32
#pragma GCC poison CONFIG_XTENSA_SIM
#pragma GCC poison CONFIG_XTENSA_VIRT
#pragma GCC poison CONFIG_XTENSA_XTFPGA
#pragma GCC poison QEMU_ARCH
#pragma GCC poison TARGET_BIG_ENDIAN
#pragma GCC poison TARGET_NAME
#pragma GCC poison TARGET_SUPPORTS_MTTCG
#pragma GCC poison TARGET_XTENSA
