# Automatically generated by configure - do not modify

all:
CONFIG_WIN32=y
QEMU_GA_MANUFACTURER=QEMU
QEMU_GA_DISTRO=Linux
QEMU_GA_VERSION=8.1.3
SRC_PATH=/c/SourceCode/qemu_lasecSimul
TARGET_DIRS=xtensa-softmmu
HAVE_GDB_BIN=/ucrt64/bin/gdb-multiarch
ROMS=
PYTHON=C:/SourceCode/qemu_lasecSimul/build-ucrt64/pyvenv/bin/python.exe -B
GENISOIMAGE=
MESON=/c/SourceCode/qemu_lasecSimul/build-ucrt64/pyvenv/bin/meson
NINJA=/ucrt64/bin/ninja
PKG_CONFIG=pkg-config
CC=cc
EXESUF=.exe
TCG_TESTS_TARGETS=
